#%RAML 1.0
title: MyS3
version: 10/13/2016 23:04:43
baseUri: https://9gn28ca086.execute-api.{region}.amazonaws.com/S3
baseUriParameters:
  region:
    required: true
    default: TODO Add Value for parameter...
    displayName: region
    type: string
securitySchemes:
  auth:
    type: Pass Through
    describedBy:
      headers:
        Authorization:
          required: true
          displayName: Authorization
          type: string
/:
  get:
    displayName: Unnammed Endpoint
    securedBy:
    - auth
    responses:
      200:
        description: 200 response
        body:
          text/plain:
            displayName: response
            description: 200 response
            type: any
      400:
        description: 400 response
        body: {}
      500:
        description: 500 response
        body: {}
/{folder}:
  uriParameters:
    folder:
      required: true
      displayName: folder
      type: string
  get:
    displayName: ByFolder
    securedBy:
    - auth
    responses:
      200:
        description: 200 response
        body:
          text/plain:
            displayName: response
            description: 200 response
            type: any
      400:
        description: 400 response
        body: {}
      500:
        description: 500 response
        body: {}
  put:
    displayName: ByFolder
    securedBy:
    - auth
    headers:
      Content-Type:
        required: false
        displayName: Content-Type
        type: string
    responses:
      200:
        description: 200 response
        body:
          text/plain:
            displayName: response
            description: 200 response
            type: any
      400:
        description: 400 response
        body: {}
      500:
        description: 500 response
        body: {}
  delete:
    displayName: ByFolder
    securedBy:
    - auth
    responses:
      200:
        description: 200 response
        body:
          text/plain:
            displayName: response
            description: 200 response
            type: any
      400:
        description: 400 response
        body: {}
      500:
        description: 500 response
        body: {}
  /{item}:
    uriParameters:
      item:
        required: true
        displayName: item
        type: string
    get:
      displayName: ByFolderAndItem
      securedBy:
      - auth
      responses:
        200:
          description: 200 response
          body:
            text/plain:
              displayName: response
              description: 200 response
              type: any
        400:
          description: 400 response
          body: {}
        500:
          description: 500 response
          body: {}
    put:
      displayName: ByFolderAndItem
      securedBy:
      - auth
      headers:
        Content-Type:
          required: false
          displayName: Content-Type
          type: string
      responses:
        200:
          description: 200 response
          body:
            text/plain:
              displayName: response
              description: 200 response
              type: any
        400:
          description: 400 response
          body: {}
        500:
          description: 500 response
          body: {}
    delete:
      displayName: ByFolderAndItem
      securedBy:
      - auth
      responses:
        200:
          description: 200 response
          body:
            text/plain:
              displayName: response
              description: 200 response
              type: any
        400:
          description: 400 response
          body: {}
        500:
          description: 500 response
          body: {}
